"""
rag_cost_analyzer.py - Per-step cost and latency analysis for a RAG pipeline.

Measures every stage of retrieval-augmented generation:
  1. Embedding    — query encoding with a local SentenceTransformer (free).
  2. Retrieval    — cosine-similarity search over pre-embedded corpus chunks.
  3. Reranking    — re-scoring the retrieved set and selecting the top-k.
  4. Context injection — assembling the final prompt string.
  5. LLM call    — actual Anthropic Messages API call; billed by token.

Cost model
----------
Sentence-transformers runs locally; its monetary cost is zero, though its
latency is measured.  All monetary cost comes from the LLM call.  The
breakdown_pct field shows what fraction of the LLM bill comes from each
token category (system prompt, query, context, response).

Chunk-size benchmark
--------------------
``benchmark_chunk_sizes`` splits a document into windows of different sizes,
embeds everything locally, retrieves the top-k chunks per size, and estimates
the LLM cost from token counts — without actually calling the LLM.  It then
recommends the chunk size that maximises retrieval quality per dollar spent.
"""

from __future__ import annotations

import json
import os
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import anthropic
import numpy as np
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

load_dotenv(Path(__file__).parent.parent / ".env")

_OUTPUT_FILE = Path(__file__).parent / "rag_cost_analysis.json"

# ---------------------------------------------------------------------------
# Pricing (USD per token) — standard (non-batch) rates
# ---------------------------------------------------------------------------

_MODEL_PRICING: dict[str, dict[str, float]] = {
    "claude-haiku-4-5":          {"input": 0.80 / 1_000_000, "output":  4.00 / 1_000_000},
    "claude-haiku-4-5-20251001": {"input": 0.80 / 1_000_000, "output":  4.00 / 1_000_000},
    "claude-sonnet-4-5":         {"input": 3.00 / 1_000_000, "output": 15.00 / 1_000_000},
    "claude-sonnet-4-6":         {"input": 3.00 / 1_000_000, "output": 15.00 / 1_000_000},
    "claude-opus-4-7":           {"input": 5.00 / 1_000_000, "output": 25.00 / 1_000_000},
}
_DEFAULT_INPUT_PRICE:  float = 3.00 / 1_000_000
_DEFAULT_OUTPUT_PRICE: float = 15.00 / 1_000_000


def _input_price(model: str) -> float:
    return _MODEL_PRICING.get(model, {"input": _DEFAULT_INPUT_PRICE})["input"]


def _output_price(model: str) -> float:
    return _MODEL_PRICING.get(model, {"output": _DEFAULT_OUTPUT_PRICE})["output"]


def _llm_cost(model: str, input_tokens: int, output_tokens: int) -> float:
    return _input_price(model) * input_tokens + _output_price(model) * output_tokens


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass
class RAGCostReport:
    """
    Full per-step cost and latency report for one RAG query.

    Attributes
    ----------
    query:
        The user question that was answered.
    model:
        Anthropic model used for the LLM call.
    chunks_retrieved:
        Number of chunks passed to the LLM as context.
    avg_similarity_score:
        Mean cosine similarity of the retrieved chunks to the query.
    top_similarity_score:
        Highest cosine similarity among retrieved chunks.

    Token counts
    ------------
    token_query:
        Tokens in the user query alone.
    token_system:
        Tokens in the system / template text.
    token_context:
        Tokens in the injected chunk context.
    token_input_total:
        Sum of all input tokens billed (system + query + context).
    token_response:
        Output tokens generated by the model.

    Latency (ms)
    ------------
    embedding_latency_ms:
        Time to encode the query with SentenceTransformer.
    retrieval_latency_ms:
        Time to compute cosine similarities over the chunk corpus.
    reranking_latency_ms:
        Time to sort and select the top-k chunks.
    context_injection_latency_ms:
        Time to assemble the final prompt string.
    llm_latency_ms:
        Wall-clock time for the Anthropic API call.
    total_latency_ms:
        End-to-end wall clock from query to response.

    Costs (USD)
    -----------
    cost_embedding_query_usd:
        Monetary cost of the embedding step ($0 for local model).
    cost_llm_input_usd:
        LLM cost for all input tokens.
    cost_llm_output_usd:
        LLM cost for output tokens.
    cost_llm_call_usd:
        Total LLM cost (input + output).
    cost_total_usd:
        Pipeline total (embedding + LLM).

    Breakdown
    ---------
    breakdown_pct:
        Fraction of ``cost_total_usd`` attributed to each token category:
        ``system``, ``query``, ``context``, ``response``, ``embedding``.

    response:
        The model's answer text.
    """

    query:                      str
    model:                      str
    chunks_retrieved:           int
    avg_similarity_score:       float
    top_similarity_score:       float

    # Tokens
    token_query:                int
    token_system:               int
    token_context:              int
    token_input_total:          int
    token_response:             int

    # Latency
    embedding_latency_ms:       float
    retrieval_latency_ms:       float
    reranking_latency_ms:       float
    context_injection_latency_ms: float
    llm_latency_ms:             float
    total_latency_ms:           float

    # Costs
    cost_embedding_query_usd:   float
    cost_llm_input_usd:         float
    cost_llm_output_usd:        float
    cost_llm_call_usd:          float
    cost_total_usd:             float

    # Breakdown
    breakdown_pct:              dict[str, float]

    response:                   str


@dataclass
class ChunkSizeAnalysis:
    """
    Cost and quality metrics for one chunk-size configuration.

    Attributes
    ----------
    chunk_size:
        Token window (in whitespace-split words) used for chunking.
    num_chunks:
        Total number of chunks the document was split into.
    top_k_retrieved:
        Number of chunks selected as context (capped at ``num_chunks``).
    avg_top_similarity:
        Mean cosine similarity of the top-k chunks to the query.
    context_tokens_est:
        Approximate token count of the assembled context (chars / 4).
    query_tokens_est:
        Approximate token count of the query.
    estimated_llm_input_tokens:
        Total estimated input tokens (system template + query + context).
    estimated_llm_cost_usd:
        Estimated LLM cost for one query using this chunk configuration.
    embedding_time_ms:
        Time to embed all chunks and the query.
    retrieval_time_ms:
        Time to rank chunks by similarity and select top-k.
    quality_cost_ratio:
        ``avg_top_similarity / estimated_llm_cost_usd`` — higher is better.
    """

    chunk_size:                 int
    num_chunks:                 int
    top_k_retrieved:            int
    avg_top_similarity:         float
    context_tokens_est:         int
    query_tokens_est:           int
    estimated_llm_input_tokens: int
    estimated_llm_cost_usd:     float
    embedding_time_ms:          float
    retrieval_time_ms:          float
    quality_cost_ratio:         float


@dataclass
class ChunkBenchmarkResult:
    """
    Cross-chunk-size benchmark outcome with an optimal-size recommendation.

    Attributes
    ----------
    query:
        The query used for all comparisons.
    model:
        Model whose pricing was used to estimate LLM costs.
    analyses:
        One :class:`ChunkSizeAnalysis` per tested chunk size, sorted by
        ``chunk_size`` ascending.
    optimal_chunk_size:
        Chunk size with the highest ``quality_cost_ratio``.
    baseline_cost_usd:
        Estimated LLM cost at the largest (most expensive) chunk size.
    optimal_cost_usd:
        Estimated LLM cost at the optimal chunk size.
    savings_vs_largest_pct:
        Percentage cost reduction vs. the largest chunk size.
    recommendation:
        Human-readable recommendation string.
    """

    query:                   str
    model:                   str
    analyses:                list[ChunkSizeAnalysis]
    optimal_chunk_size:      int
    baseline_cost_usd:       float
    optimal_cost_usd:        float
    savings_vs_largest_pct:  float
    recommendation:          str


# ---------------------------------------------------------------------------
# RAGCostAnalyzer
# ---------------------------------------------------------------------------

_SYSTEM_TEMPLATE = (
    "Answer the question using ONLY the provided context passages. "
    "If the answer cannot be found in the context, say so explicitly.\n\n"
    "Context:\n{context}"
)
# Fixed overhead from the system template excluding the context slot
_SYSTEM_OVERHEAD_CHARS = len(_SYSTEM_TEMPLATE.replace("{context}", ""))


class RAGCostAnalyzer:
    """
    Measures and reports the per-step cost of a RAG query pipeline.

    Parameters
    ----------
    embedding_model:
        HuggingFace sentence-transformers model name.  Downloaded on first
        use (~22 MB for ``all-MiniLM-L6-v2``).
    top_k:
        Number of chunks to retrieve and inject as context.
    max_tokens:
        Maximum tokens for the LLM response.
    api_key:
        Anthropic API key; falls back to ``ANTHROPIC_API_KEY`` env var.
    output_file:
        Path for persisting analyses.
    """

    def __init__(
        self,
        embedding_model: str           = "all-MiniLM-L6-v2",
        top_k:           int           = 3,
        max_tokens:      int           = 512,
        api_key:         Optional[str] = None,
        output_file:     Optional[Path] = None,
    ) -> None:
        print(f"  Loading embedding model '{embedding_model}' ...", end=" ", flush=True)
        self._embedder        = SentenceTransformer(embedding_model)
        self._embedding_model = embedding_model
        print("ready.")

        self._client     = anthropic.Anthropic(
            api_key=api_key or os.environ.get("ANTHROPIC_API_KEY", "")
        )
        self._top_k      = top_k
        self._max_tokens = max_tokens
        self._out_file   = output_file or _OUTPUT_FILE

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _split_into_chunks(text: str, chunk_size: int, overlap: int = 20) -> list[str]:
        """
        Split *text* into overlapping word-count windows.

        Parameters
        ----------
        text:
            Full document text.
        chunk_size:
            Target number of whitespace-delimited words per chunk.
        overlap:
            Number of words shared between consecutive chunks (sliding window).

        Returns
        -------
        list[str]
            Non-empty chunk strings.
        """
        words  = text.split()
        step   = max(1, chunk_size - overlap)
        chunks = []
        for start in range(0, len(words), step):
            chunk = " ".join(words[start : start + chunk_size])
            if chunk:
                chunks.append(chunk)
        return chunks

    def _embed(self, texts: list[str]) -> np.ndarray:
        """Return a (N, D) float32 embedding matrix for *texts*."""
        return self._embedder.encode(texts, convert_to_numpy=True, show_progress_bar=False)

    @staticmethod
    def _cos_sim(query_vec: np.ndarray, corpus_mat: np.ndarray) -> np.ndarray:
        """Return 1-D cosine similarity array (len = len(corpus))."""
        return cosine_similarity(query_vec.reshape(1, -1), corpus_mat)[0]

    @staticmethod
    def _approx_tokens(text: str) -> int:
        """Rough token estimate: 4 characters per token (used for benchmarks only)."""
        return max(1, len(text) // 4)

    def _build_prompt(self, query: str, chunks: list[str]) -> str:
        """Assemble the full user-facing message (context already injected)."""
        context = "\n\n---\n\n".join(
            f"[Chunk {i+1}]\n{chunk}" for i, chunk in enumerate(chunks)
        )
        system_body = _SYSTEM_TEMPLATE.format(context=context)
        # Return as the user message; system prompt is passed separately in the API call
        return system_body, query

    # ------------------------------------------------------------------
    # analyze
    # ------------------------------------------------------------------

    def analyze(
        self,
        query:            str,
        retrieved_chunks: list[str],
        model:            str = "claude-haiku-4-5",
    ) -> RAGCostReport:
        """
        Run a full RAG pipeline on *query* using *retrieved_chunks* as the
        corpus, measure every step, and return a :class:`RAGCostReport`.

        The method performs: embed query -> embed & rerank chunks -> inject
        context -> count tokens -> call LLM.

        Parameters
        ----------
        query:
            User question.
        retrieved_chunks:
            Candidate text passages (already retrieved from a vector store or
            passed directly).  The method re-embeds them for reranking.
        model:
            Anthropic model to call for the final answer.

        Returns
        -------
        RAGCostReport
            Fully populated cost and latency report.
        """
        t_pipeline_start = time.perf_counter()

        # ---- Step 1: Embed query ----------------------------------------
        t0 = time.perf_counter()
        query_vec = self._embed([query])[0]
        embedding_latency_ms = (time.perf_counter() - t0) * 1_000

        # ---- Step 2: Embed corpus (for reranking) -----------------------
        t0 = time.perf_counter()
        corpus_mat = self._embed(retrieved_chunks)
        sims       = self._cos_sim(query_vec, corpus_mat)
        retrieval_latency_ms = (time.perf_counter() - t0) * 1_000

        # ---- Step 3: Rerank — select top-k ------------------------------
        t0 = time.perf_counter()
        k          = min(self._top_k, len(retrieved_chunks))
        top_idx    = np.argsort(sims)[::-1][:k]
        top_chunks = [retrieved_chunks[i] for i in top_idx]
        top_sims   = sims[top_idx]
        reranking_latency_ms = (time.perf_counter() - t0) * 1_000

        # ---- Step 4: Context injection ----------------------------------
        t0 = time.perf_counter()
        system_text, user_text = self._build_prompt(query, top_chunks)
        context_injection_latency_ms = (time.perf_counter() - t0) * 1_000

        # ---- Step 5: Count tokens (accurate, no generation cost) --------
        token_count = self._client.messages.count_tokens(
            model    = model,
            system   = system_text,
            messages = [{"role": "user", "content": user_text}],
        )
        total_input_tokens = token_count.input_tokens

        # Approximate per-category token split for breakdown
        token_query_est   = self._approx_tokens(query)
        token_context_est = self._approx_tokens(
            "\n\n---\n\n".join(f"[Chunk {i+1}]\n{c}" for i, c in enumerate(top_chunks))
        )
        token_system_est  = max(0, total_input_tokens - token_query_est - token_context_est)

        # ---- Step 6: LLM call -------------------------------------------
        t0 = time.perf_counter()
        response_msg = self._client.messages.create(
            model      = model,
            max_tokens = self._max_tokens,
            system     = system_text,
            messages   = [{"role": "user", "content": user_text}],
        )
        llm_latency_ms = (time.perf_counter() - t0) * 1_000

        actual_input  = response_msg.usage.input_tokens
        actual_output = response_msg.usage.output_tokens
        response_text = response_msg.content[0].text if response_msg.content else ""

        total_latency_ms = (time.perf_counter() - t_pipeline_start) * 1_000

        # ---- Costs ------------------------------------------------------
        cost_embed   = 0.0   # local sentence-transformers
        cost_input   = _input_price(model)  * actual_input
        cost_output  = _output_price(model) * actual_output
        cost_llm     = cost_input + cost_output
        cost_total   = cost_embed + cost_llm

        # Per-category cost for breakdown (proportional split on input side)
        def _share(tok_est: int, total_est: int, total_cost: float) -> float:
            return (tok_est / total_est * total_cost) if total_est > 0 else 0.0

        total_est = token_query_est + token_context_est + token_system_est
        breakdown_pct: dict[str, float] = {
            "embedding_pct":  0.0,
            "system_pct":     round(_share(token_system_est,  total_est, cost_input) / cost_total * 100, 1) if cost_total else 0.0,
            "query_pct":      round(_share(token_query_est,   total_est, cost_input) / cost_total * 100, 1) if cost_total else 0.0,
            "context_pct":    round(_share(token_context_est, total_est, cost_input) / cost_total * 100, 1) if cost_total else 0.0,
            "response_pct":   round(cost_output / cost_total * 100, 1) if cost_total else 0.0,
        }

        report = RAGCostReport(
            query                        = query,
            model                        = model,
            chunks_retrieved             = k,
            avg_similarity_score         = float(np.mean(top_sims)),
            top_similarity_score         = float(top_sims[0]) if len(top_sims) else 0.0,
            token_query                  = token_query_est,
            token_system                 = token_system_est,
            token_context                = token_context_est,
            token_input_total            = actual_input,
            token_response               = actual_output,
            embedding_latency_ms         = round(embedding_latency_ms, 1),
            retrieval_latency_ms         = round(retrieval_latency_ms, 1),
            reranking_latency_ms         = round(reranking_latency_ms, 1),
            context_injection_latency_ms = round(context_injection_latency_ms, 1),
            llm_latency_ms               = round(llm_latency_ms, 1),
            total_latency_ms             = round(total_latency_ms, 1),
            cost_embedding_query_usd     = cost_embed,
            cost_llm_input_usd           = round(cost_input,  8),
            cost_llm_output_usd          = round(cost_output, 8),
            cost_llm_call_usd            = round(cost_llm,    8),
            cost_total_usd               = round(cost_total,  8),
            breakdown_pct                = breakdown_pct,
            response                     = response_text,
        )
        return report

    # ------------------------------------------------------------------
    # benchmark_chunk_sizes
    # ------------------------------------------------------------------

    def benchmark_chunk_sizes(
        self,
        query:       str,
        document:    str,
        chunk_sizes: list[int]    = None,
        top_k:       Optional[int] = None,
        model:       str           = "claude-haiku-4-5",
    ) -> ChunkBenchmarkResult:
        """
        Compare retrieval quality and estimated LLM cost across chunk sizes.

        No LLM calls are made; costs are estimated from token counts.
        Use this to choose a chunk size before paying for a live pipeline.

        Parameters
        ----------
        query:
            User question used to rank chunk relevance.
        document:
            Full document text to chunk.
        chunk_sizes:
            List of word-count window sizes to evaluate.
            Defaults to ``[128, 256, 512, 1024]``.
        top_k:
            Chunks to retrieve per configuration.  Defaults to
            ``self._top_k``.
        model:
            Model whose pricing is used for cost estimation.

        Returns
        -------
        ChunkBenchmarkResult
            Contains one :class:`ChunkSizeAnalysis` per chunk size plus
            the optimal recommendation.
        """
        if chunk_sizes is None:
            chunk_sizes = [128, 256, 512, 1024]
        k = top_k if top_k is not None else self._top_k

        # System template overhead token estimate (fixed across chunk sizes)
        system_overhead_tokens = self._approx_tokens(
            _SYSTEM_TEMPLATE.replace("{context}", "")
        )
        query_tokens_est = self._approx_tokens(query)

        # Embed the query once
        t0        = time.perf_counter()
        query_vec = self._embed([query])[0]
        _query_embed_ms = (time.perf_counter() - t0) * 1_000

        analyses: list[ChunkSizeAnalysis] = []

        for cs in sorted(chunk_sizes):
            chunks = self._split_into_chunks(document, cs)
            if not chunks:
                continue

            # Embed corpus
            t0           = time.perf_counter()
            corpus_mat   = self._embed(chunks)
            embed_ms     = (time.perf_counter() - t0) * 1_000 + _query_embed_ms

            # Retrieve top-k
            t0           = time.perf_counter()
            sims         = self._cos_sim(query_vec, corpus_mat)
            actual_k     = min(k, len(chunks))
            top_idx      = np.argsort(sims)[::-1][:actual_k]
            top_chunks   = [chunks[i] for i in top_idx]
            top_sims     = sims[top_idx]
            retrieval_ms = (time.perf_counter() - t0) * 1_000

            context_text       = "\n\n---\n\n".join(
                f"[Chunk {i+1}]\n{c}" for i, c in enumerate(top_chunks)
            )
            context_tokens_est = self._approx_tokens(context_text)
            total_input_est    = system_overhead_tokens + query_tokens_est + context_tokens_est

            # Output token estimate: assume ~200 tokens average response
            output_tokens_est  = 200
            est_cost = _llm_cost(model, total_input_est, output_tokens_est)

            qcr = float(np.mean(top_sims)) / est_cost if est_cost > 0 else 0.0

            analyses.append(ChunkSizeAnalysis(
                chunk_size                 = cs,
                num_chunks                 = len(chunks),
                top_k_retrieved            = actual_k,
                avg_top_similarity         = round(float(np.mean(top_sims)), 4),
                context_tokens_est         = context_tokens_est,
                query_tokens_est           = query_tokens_est,
                estimated_llm_input_tokens = total_input_est,
                estimated_llm_cost_usd     = round(est_cost, 8),
                embedding_time_ms          = round(embed_ms, 1),
                retrieval_time_ms          = round(retrieval_ms, 1),
                quality_cost_ratio         = round(qcr, 2),
            ))

        if not analyses:
            raise ValueError("No valid analyses produced — check document and chunk_sizes.")

        # Optimal = best quality/cost ratio
        optimal     = max(analyses, key=lambda a: a.quality_cost_ratio)
        baseline    = max(analyses, key=lambda a: a.chunk_size)
        savings_pct = (
            (baseline.estimated_llm_cost_usd - optimal.estimated_llm_cost_usd)
            / baseline.estimated_llm_cost_usd * 100
            if baseline.estimated_llm_cost_usd > 0 else 0.0
        )

        recommendation = (
            f"Optimal chunk size for this document is {optimal.chunk_size} words "
            f"(quality/cost ratio {optimal.quality_cost_ratio:.2f}). "
            f"Estimated saving: {savings_pct:.1f}% vs the largest chunk size "
            f"({baseline.chunk_size} words)."
        )

        return ChunkBenchmarkResult(
            query                  = query,
            model                  = model,
            analyses               = analyses,
            optimal_chunk_size     = optimal.chunk_size,
            baseline_cost_usd      = baseline.estimated_llm_cost_usd,
            optimal_cost_usd       = optimal.estimated_llm_cost_usd,
            savings_vs_largest_pct = round(savings_pct, 1),
            recommendation         = recommendation,
        )

    # ------------------------------------------------------------------
    # save_analysis
    # ------------------------------------------------------------------

    def save_analysis(
        self,
        report:    Optional[RAGCostReport]      = None,
        benchmark: Optional[ChunkBenchmarkResult] = None,
    ) -> Path:
        """
        Persist *report* and/or *benchmark* to ``rag_cost_analysis.json``.

        Overwrites the previous file.  Pass either or both arguments.

        Parameters
        ----------
        report:
            :class:`RAGCostReport` from :meth:`analyze`, or ``None``.
        benchmark:
            :class:`ChunkBenchmarkResult` from :meth:`benchmark_chunk_sizes`,
            or ``None``.

        Returns
        -------
        Path
            Absolute path of the written file.
        """
        payload: dict = {
            "saved_at": datetime.now(timezone.utc).isoformat(),
        }
        if benchmark is not None:
            payload["benchmark"] = asdict(benchmark)
        if report is not None:
            payload["analysis"] = asdict(report)

        self._out_file.write_text(
            json.dumps(payload, indent=2, default=str),
            encoding="utf-8",
        )
        return self._out_file


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import textwrap

    # ------------------------------------------------------------------
    # 1. Generate a ~500-line technical document
    # ------------------------------------------------------------------
    _PARAGRAPHS = [
        # RAG & embeddings
        "Retrieval-Augmented Generation (RAG) combines a vector retrieval step with a generative language model. "
        "Rather than relying solely on parametric knowledge baked into model weights, RAG retrieves relevant passages "
        "from an external corpus at inference time and injects them into the prompt. This reduces hallucination and "
        "keeps responses grounded in up-to-date source material.",

        "Embedding models project text into a high-dimensional vector space where semantically similar passages cluster "
        "together. Dense retrieval with models such as sentence-transformers/all-MiniLM-L6-v2 outperforms sparse BM25 "
        "on most semantic-search benchmarks while remaining inexpensive to run locally. The embedding dimension is "
        "typically 384 or 768 floats per passage.",

        "Chunk size is a critical hyperparameter in RAG pipelines. Smaller chunks (64-128 words) provide precise "
        "retrieval at the cost of losing broader context. Larger chunks (512-1024 words) preserve discourse structure "
        "but dilute the semantic signal and inflate the LLM context window, increasing per-query cost. Most production "
        "systems benchmark several sizes and choose the one that maximises answer quality per dollar spent.",

        "Cosine similarity is the standard distance metric for dense retrieval. Given a query vector q and a corpus "
        "matrix C, the score for each passage is dot(q, c_i) / (||q|| * ||c_i||). Because sentence-transformer "
        "embeddings are L2-normalised, this simplifies to a pure dot product, enabling fast BLAS-accelerated search.",

        "Approximate nearest-neighbour (ANN) indexes such as FAISS, ScaNN, or HNSW scale dense retrieval to millions "
        "of documents. At smaller corpus sizes (<100k chunks), exact search with numpy matmul is often faster due to "
        "the absence of index-build overhead. The crossover point depends on hardware and embedding dimension.",

        # Token economics
        "Large language model APIs charge per token — both input (prompt) and output (completion). In a RAG pipeline, "
        "the injected context typically dominates input-token cost: a top-3 retrieval with 512-word chunks can add "
        "500-800 tokens to every query, dwarfing the 10-20 tokens of the question itself. Cost-conscious teams measure "
        "context-to-query token ratios and set hard caps on context length.",

        "The Anthropic pricing model charges different rates for input and output tokens. As of 2025, claude-haiku-4-5 "
        "costs $0.80 per million input tokens and $4.00 per million output tokens. For a RAG workload where 80% of "
        "tokens are context, the effective cost per query is dominated by the input rate. Choosing a smaller model or "
        "compressing context with extractive summarisation are common cost-reduction strategies.",

        "Prompt caching on the Anthropic API allows repeated system-prompt prefixes to be stored server-side, billed "
        "at 10% of the normal input rate on subsequent requests. For RAG with a static system prompt and frequently "
        "reused document chunks, caching can cut input costs by 40-60%. Cache hits are indicated by the "
        "cache_read_input_tokens field in the usage response.",

        "Streaming responses lower perceived latency by delivering tokens progressively. The time-to-first-token (TTFT) "
        "metric measures the gap between request dispatch and the first output token arriving. For interactive RAG "
        "applications, TTFT is more important than total latency; users tolerate long completions if text starts "
        "appearing quickly. Typical TTFT on claude-haiku-4-5 is 200-600 ms.",

        "Batch processing via the Anthropic Batch API processes requests asynchronously at 50% of real-time pricing. "
        "RAG pipelines for non-interactive workloads — nightly document digests, bulk QA evaluation, offline "
        "annotation — are ideal batch candidates. Batches can contain up to 10,000 requests and complete within 24 h.",

        # Latency & SLAs
        "End-to-end RAG latency has four components: embedding (10-100 ms local), retrieval (1-50 ms for <1M chunks), "
        "context assembly (<1 ms), and LLM inference (200 ms to 3 s depending on model and output length). The LLM "
        "call dominates in most configurations; reducing max_tokens or switching to a smaller model has the largest "
        "impact on p99 latency.",

        "SLA tiers for RAG applications typically target p50 < 500 ms, p90 < 1500 ms, and p99 < 3000 ms for "
        "interactive workloads. Achieving these thresholds requires careful model selection, context length caps, and "
        "streaming delivery. Asynchronous pre-fetching — embedding the query before the user finishes typing — can "
        "mask embedding latency entirely.",

        "Rolling-window percentile monitoring catches SLA regressions faster than simple averages. A 5-minute window "
        "of 50 samples is sufficient to detect p99 breaches within two minutes of an incident starting. Alerts should "
        "fire on consecutive window violations rather than single-point anomalies to suppress false positives from "
        "transient API blips.",

        # Vector stores
        "Vector databases such as Pinecone, Weaviate, Qdrant, and Chroma store embeddings alongside metadata and "
        "support filtered ANN search. Metadata filters (e.g., date range, document type) can dramatically reduce the "
        "effective corpus size, improving both retrieval precision and latency. Hybrid search — combining dense "
        "vectors with keyword BM25 scores — often outperforms either modality alone.",

        "Index freshness is a key operational concern for RAG. Documents added since the last index rebuild are "
        "invisible to the retriever until their embeddings are inserted. Real-time indexing pipelines use streaming "
        "ingestion (Kafka, Kinesis) to keep the vector store within seconds of the source corpus. Incremental "
        "re-embedding is cheap per document but requires careful version management when the embedding model changes.",

        # Reranking
        "Cross-encoder rerankers such as ms-marco-MiniLM-L-6-v2 provide more accurate relevance scores than "
        "bi-encoder (embedding) models because they attend jointly over query and passage. The trade-off is speed: "
        "a bi-encoder embeds query and passage independently and compares with a dot product; a cross-encoder runs "
        "a full forward pass over the concatenated pair. Reranking is therefore applied only to the top-k bi-encoder "
        "results (typically top-20 -> rerank -> top-3).",

        "Reranking latency scales linearly with the number of candidate passages. At 20 candidates and a 6-layer "
        "cross-encoder, reranking adds roughly 80-200 ms on CPU. GPU acceleration or a smaller reranker model can "
        "reduce this to 10-30 ms. In latency-sensitive applications, reranking is often skipped in favour of a "
        "higher-quality bi-encoder.",

        # Evaluation
        "RAG evaluation frameworks such as RAGAS measure retrieval quality (context precision, context recall) and "
        "generation quality (faithfulness, answer relevancy) independently. Context precision measures how many of "
        "the retrieved passages are actually relevant; context recall measures how many of the relevant passages "
        "were retrieved. Both are required for a complete quality picture.",

        "Offline evaluation using a held-out question-answer benchmark is essential before deploying a new RAG "
        "configuration to production. Common benchmarks include Natural Questions (open-domain QA), HotpotQA "
        "(multi-hop reasoning), and domain-specific curated sets. Automated LLM judges (GPT-4 or Claude as "
        "evaluator) correlate well with human ratings at a fraction of the cost.",

        "A/B testing RAG configurations in production requires careful traffic splitting and metric collection. "
        "Key metrics are answer acceptance rate (user thumbs-up), task completion rate, and follow-up question "
        "rate (a proxy for answer incompleteness). Statistical significance requires hundreds to thousands of "
        "paired queries depending on effect size and desired power.",

        # Chunking strategies
        "Fixed-size chunking (splitting every N words) is simple but ignores document structure. Sentence-based "
        "chunking preserves grammatical units but produces highly variable chunk sizes. Paragraph-based chunking "
        "aligns with natural discourse boundaries and is preferred for structured documents such as technical "
        "manuals, legal contracts, and academic papers.",

        "Hierarchical chunking stores both coarse summaries and fine-grained passages, enabling a two-stage "
        "retrieval: first retrieve the relevant section summary, then the specific sub-passage. This reduces the "
        "index size for the initial retrieval pass and improves precision for long documents with many thematically "
        "distinct sections.",

        "Sliding-window chunking with overlap prevents relevant information from being split across chunk "
        "boundaries. An overlap of 10-20% of the chunk size is typical. The overlap tokens are redundant between "
        "adjacent chunks, increasing index size and embedding time proportionally; the quality improvement "
        "usually justifies the overhead for documents with dense cross-sentence dependencies.",

        # Cost optimisation
        "Context compression techniques reduce the number of tokens injected into the LLM prompt without sacrificing "
        "answer quality. Extractive compression selects the most relevant sentences from retrieved chunks; abstractive "
        "compression rewrites them into a tighter summary. A small, fast model (e.g., claude-haiku-4-5) can compress "
        "context before passing it to a larger model, reducing net token cost.",

        "Query rewriting improves retrieval recall by expanding or reformulating the user question before embedding. "
        "Techniques include HyDE (hypothetical document embeddings — generate a fake answer and embed it as the "
        "query), sub-question decomposition, and synonym expansion. Query rewriting adds a small LLM call (~50 "
        "tokens) but can improve top-k recall by 5-15 percentage points on complex questions.",

        "Caching at the retrieval layer stores (query_embedding, top_k_results) pairs keyed by embedding vector "
        "(approximate nearest-neighbour in embedding space). Cache hit rates of 20-40% are common for "
        "customer-service RAG where many users ask semantically similar questions. Each cache hit eliminates both "
        "the vector search and the LLM call, yielding near-100% cost and latency savings for those queries.",

        # Infrastructure
        "Containerised RAG deployments on Kubernetes separate the embedding service, vector store, and LLM gateway "
        "into independently scalable components. The embedding service can autoscale on CPU utilisation; the LLM "
        "gateway scales on request queue depth. Separating these tiers prevents a slow LLM response from blocking "
        "the embedding service from handling new queries.",

        "Observability for RAG pipelines requires distributed tracing (trace_id propagated through all services), "
        "structured logging (JSON with consistent field names), and metrics (Prometheus counters and histograms). "
        "Key counters: queries_total, cache_hits_total, retrieval_latency_seconds, llm_latency_seconds, "
        "tokens_in_total, tokens_out_total, cost_usd_total.",

        "Model versioning in RAG requires co-versioning the embedding model and the vector index. Re-embedding the "
        "corpus whenever the embedding model changes is mandatory; vectors from different model versions are not "
        "comparable. Blue-green index deployments allow zero-downtime upgrades by building the new index in parallel "
        "and switching traffic atomically.",

        "Security considerations for RAG include prompt injection (malicious instructions embedded in retrieved "
        "documents), PII leakage (sensitive content surfaced from the corpus into LLM responses), and access "
        "control (ensuring users can only retrieve documents they are authorised to read). Retrieval-time "
        "permission filtering based on user identity is the standard mitigation for the last issue.",
    ]

    # Repeat paragraphs to reach ~500 lines of text
    _LINES: list[str] = []
    for p in _PARAGRAPHS * 4:
        wrapped = textwrap.fill(p, width=100)
        _LINES.extend(wrapped.splitlines())
        _LINES.append("")

    _DOCUMENT = "\n".join(_LINES[:500])
    _QUERY    = (
        "What is the impact of chunk size on RAG pipeline cost and retrieval quality, "
        "and what strategies can reduce LLM token costs?"
    )
    _MODEL     = "claude-haiku-4-5"

    sep  = "=" * 70
    thin = "-" * 70

    # ------------------------------------------------------------------
    # 2. Initialise analyzer
    # ------------------------------------------------------------------
    print(f"\n{sep}")
    print("  RAG COST ANALYZER DEMO")
    print(sep)

    analyzer = RAGCostAnalyzer(
        embedding_model = "all-MiniLM-L6-v2",
        top_k           = 3,
        max_tokens      = 400,
    )

    print(f"\n  Document: {len(_LINES[:500])} lines / {len(_DOCUMENT.split())} words")
    print(f"  Query   : {_QUERY[:80]}...")
    print(f"  Model   : {_MODEL}\n")

    # ------------------------------------------------------------------
    # 3. Benchmark chunk sizes
    # ------------------------------------------------------------------
    print(sep)
    print("  CHUNK-SIZE BENCHMARK  (no LLM calls)")
    print(sep)

    bench = analyzer.benchmark_chunk_sizes(
        query       = _QUERY,
        document    = _DOCUMENT,
        chunk_sizes = [128, 256, 512],
        model       = _MODEL,
    )

    # Header
    print(
        f"\n  {'Size':>5}  {'Chunks':>6}  {'Top-k':>5}  {'AvgSim':>7}  "
        f"{'CtxTok':>7}  {'TotalTok':>8}  {'Est.Cost$':>10}  {'Q/C ratio':>10}  "
        f"{'EmbMs':>6}  {'RetMs':>6}"
    )
    print(f"  {thin}")
    for a in bench.analyses:
        print(
            f"  {a.chunk_size:>5}  {a.num_chunks:>6}  {a.top_k_retrieved:>5}  "
            f"{a.avg_top_similarity:>7.4f}  {a.context_tokens_est:>7}  "
            f"{a.estimated_llm_input_tokens:>8}  ${a.estimated_llm_cost_usd:>9.7f}  "
            f"{a.quality_cost_ratio:>10.2f}  "
            f"{a.embedding_time_ms:>6.0f}  {a.retrieval_time_ms:>6.1f}"
        )

    print(f"\n  Optimal chunk size : {bench.optimal_chunk_size} words")
    print(f"  Savings vs largest : {bench.savings_vs_largest_pct:.1f}%")
    print(f"  Recommendation     : {bench.recommendation}")

    # ------------------------------------------------------------------
    # 4. Full RAG analysis with optimal chunk size
    # ------------------------------------------------------------------
    print(f"\n{sep}")
    print(f"  FULL RAG ANALYSIS  (chunk_size={bench.optimal_chunk_size}, live LLM call)")
    print(sep)

    # Build corpus with optimal chunk size and retrieve top chunks manually
    optimal_chunks = analyzer._split_into_chunks(_DOCUMENT, bench.optimal_chunk_size)
    print(f"\n  Corpus: {len(optimal_chunks)} chunks  |  Calling LLM ...", end=" ", flush=True)

    report = analyzer.analyze(
        query            = _QUERY,
        retrieved_chunks = optimal_chunks,
        model            = _MODEL,
    )
    print("done.\n")

    # ---- Step latency table
    print(f"  LATENCY BREAKDOWN")
    print(f"  {thin}")
    steps = [
        ("1. Embedding (query)",  report.embedding_latency_ms),
        ("2. Retrieval (cosine)", report.retrieval_latency_ms),
        ("3. Reranking",          report.reranking_latency_ms),
        ("4. Context injection",  report.context_injection_latency_ms),
        ("5. LLM call",           report.llm_latency_ms),
    ]
    for name, ms in steps:
        bar_w  = 30
        pct    = ms / report.total_latency_ms * 100 if report.total_latency_ms else 0
        filled = round(pct * bar_w / 100)
        bar    = "[" + "#" * filled + "-" * (bar_w - filled) + "]"
        print(f"  {name:<28}  {ms:>8.1f}ms  {bar}  {pct:5.1f}%")
    print(f"  {'TOTAL':<28}  {report.total_latency_ms:>8.1f}ms")

    # ---- Token table
    print(f"\n  TOKEN BREAKDOWN")
    print(f"  {thin}")
    print(f"  {'Category':<28}  {'Tokens':>8}  {'Cost USD':>14}")
    print(f"  {thin}")
    in_p = _input_price(_MODEL)
    out_p = _output_price(_MODEL)
    rows = [
        ("System prompt (est.)",  report.token_system,   report.token_system  * in_p),
        ("Query",                 report.token_query,    report.token_query   * in_p),
        ("Context (chunks)",      report.token_context,  report.token_context * in_p),
        ("Input total (actual)",  report.token_input_total, report.cost_llm_input_usd),
        ("Response",              report.token_response, report.cost_llm_output_usd),
    ]
    for name, tok, cost in rows:
        print(f"  {name:<28}  {tok:>8}  ${cost:>13.8f}")
    print(f"  {thin}")
    print(f"  {'Embedding (local)':<28}  {'---':>8}  ${report.cost_embedding_query_usd:>13.8f}")
    print(f"  {'TOTAL':<28}  {'---':>8}  ${report.cost_total_usd:>13.8f}")

    # ---- Cost breakdown
    print(f"\n  COST BREAKDOWN (%)")
    print(f"  {thin}")
    for key, pct in report.breakdown_pct.items():
        bar_w  = 30
        filled = round(pct * bar_w / 100)
        bar    = "[" + "#" * filled + "-" * (bar_w - filled) + "]"
        print(f"  {key:<28}  {bar}  {pct:5.1f}%")

    # ---- Retrieval quality
    print(f"\n  RETRIEVAL QUALITY")
    print(f"  {thin}")
    print(f"  Chunks used         : {report.chunks_retrieved}")
    print(f"  Top similarity      : {report.top_similarity_score:.4f}")
    print(f"  Avg similarity      : {report.avg_similarity_score:.4f}")

    # ---- Response
    print(f"\n  LLM RESPONSE")
    print(f"  {thin}")
    for line in textwrap.wrap(report.response, width=68):
        print(f"  {line}")

    # ------------------------------------------------------------------
    # 5. Save & summary
    # ------------------------------------------------------------------
    out_path = analyzer.save_analysis(report=report, benchmark=bench)
    print(f"\n  Analysis saved to: {out_path}")
    print(f"{sep}\n")
